# vim8_install/tasks/main.yml
---
- name: Gathering facts
  ansible.builtin.setup:
    gather_subset: min

- name: Assert that this is EL 7 Linux
  ansible.builtin.assert:
    that:
      - ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      - ansible_distribution_major_version == '7'
    success_msg: EL 7 detected, installing Vim from source
    fail_msg: This role only supports CentOS 7 or RHEL 7 for now

- name: Checking for existing Vim
  ansible.builtin.stat:
    path: /usr/local/bin/vim
  register: vimcheck

- name: Installing Vim
  block:
    - name: Installing dependencies
      ansible.builtin.yum:
        name:
          - autoconf
          - gcc
          - git
          - make
          - ncurses-devel
          - automake
        state: installed

    - name: Cloning Vim Github repo
      ansible.builtin.git:
        repo: https://github.com/vim/vim.git
        version: master
        depth: 1
        dest: /tmp/vim

    - name: Running make
      community.general.make:
        chdir: /tmp/vim/src

    - name: Running make install
      community.general.make:
        chdir: /tmp/vim/src
        target: install

    - name: Cleaning up
      ansible.builtin.file:
        path: /tmp/vim
        state: absent
  when: not vimcheck.stat.exists

- name: Creating /etc/profile.d/vim.sh
  ansible.builtin.copy:
    content: |
      PATH=/usr/local/bin:$PATH;export PATH
    dest: /etc/profile.d/vim.sh
    owner: root
    group: root
    mode: 0644
...
