# tasks/main.yml
---
- name: Gathering facts
  ansible.builtin.setup:
    gather_subset: min

- name: Setting detected_os
  ansible.builtin.set_fact:
    detected_os: '{{ ansible_distribution }} {{ ansible_distribution_version }}'

- name: Checking for /usr/local/bin/vim
  ansible.builtin.stat:
    path: /usr/local/bin/vim
  register: vimcheck

- name: Installing Vim
  block:
    - name: Installing EL7 dependencies
      ansible.builtin.yum:
        name:
          - autoconf
          - gcc
          - git
          - make
          - ncurses-devel
          - automake
        state: installed
      when: detected_os is search('CentOS 7') or
            detected_os is search('RedHat 7')

    - name: Installing Ubuntu dependencies
      ansible.builtin.apt:
        name:
          - clang
          - gcc
          - make
        state: present
      when: detected_os is search('Ubuntu')

    - name: Cloning Vim Github repo
      ansible.builtin.git:
        repo: https://github.com/vim/vim.git
        version: master
        depth: 1
        dest: /tmp/vim

    - name: Running make
      community.general.make:
        chdir: /tmp/vim/src

    - name: Running make install
      community.general.make:
        chdir: /tmp/vim/src
        target: install

    - name: Cleaning up
      ansible.builtin.file:
        path: /tmp/vim
        state: absent
  when: not vimcheck.stat.exists

- name: Creating /etc/profile.d/vim.sh
  ansible.builtin.copy:
    content: |
      PATH=/usr/local/bin:$PATH;export PATH
    dest: /etc/profile.d/vim.sh
    owner: root
    group: root
    mode: 0644
...
