# file: molecule/default/molecule.yml
---
scenario:
  name: default
  test_sequence:
    - destroy
    # - dependency
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - destroy

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: centos7
    image: 'centos:7.9.2009'

  - name: almalinux8
    image: 'almalinux:8'

  - name: ubuntu20
    image: 'ubuntu:focal'

  - name: ubuntu22
    image: 'ubuntu:jammy'

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: community.general.yaml
      stderr_callback: community.general.yaml
  inventory:
    host_vars:
      ansible_user: ansible
...
