# file: molecule/ubuntu/molecule.yml
---
scenario:
  name: ubuntu
  test_sequence:
    - destroy
    # - dependency
    - syntax
    - create
    # - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - destroy

dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: ubuntu20
    image: 'ubuntu:focal'

  - name: ubuntu22
    image: 'ubuntu:jammy'
...
